"""Add like count column to commnets

Revision ID: 27b0e0aa69a7
Revises: 49a5d0a98206
Create Date: 2026-01-10 20:16:59.146565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b0e0aa69a7'
down_revision: Union[str, Sequence[str], None] = '49a5d0a98206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('like_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'like_count')
    # ### end Alembic commands ###
