"""Add read time column to posts table

Revision ID: 49a5d0a98206
Revises: cced51142379
Create Date: 2026-01-06 23:14:28.837886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a5d0a98206'
down_revision: Union[str, Sequence[str], None] = 'cced51142379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('read_time_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'read_time_minutes')
    # ### end Alembic commands ###
