"""Add tag slug field

Revision ID: 5ec3fcd6b105
Revises: 64a015786441
Create Date: 2025-12-30 19:33:26.689693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec3fcd6b105'
down_revision: Union[str, Sequence[str], None] = '64a015786441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'tags', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('tags', 'slug')
    # ### end Alembic commands ###
