"""Add tldr field to posts

Revision ID: 5fe82ffd4a6d
Revises: 5484c998fa31
Create Date: 2026-01-05 21:18:07.121090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe82ffd4a6d'
down_revision: Union[str, Sequence[str], None] = '5484c998fa31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tldr', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tldr')
    # ### end Alembic commands ###
