"""Add depth column to commnets

Revision ID: 7e8c20283b1f
Revises: 27b0e0aa69a7
Create Date: 2026-01-11 03:27:22.782248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8c20283b1f'
down_revision: Union[str, Sequence[str], None] = '27b0e0aa69a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('depth', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'depth')
    # ### end Alembic commands ###
