"""Remove email from comments table

Revision ID: 8bc88c9198e6
Revises: 7e8c20283b1f
Create Date: 2026-01-13 23:14:10.517318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc88c9198e6'
down_revision: Union[str, Sequence[str], None] = '7e8c20283b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'author_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
