"""Add cascading deletes to posts and tags

Revision ID: 9eb5c0cc39b9
Revises: 5ec3fcd6b105
Create Date: 2025-12-30 20:17:46.482389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb5c0cc39b9'
down_revision: Union[str, Sequence[str], None] = '5ec3fcd6b105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_tags_post_id_fkey'), 'post_tags', type_='foreignkey')
    op.drop_constraint(op.f('post_tags_tag_id_fkey'), 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key(op.f('post_tags_tag_id_fkey'), 'post_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('post_tags_post_id_fkey'), 'post_tags', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
