"""Add summary and featured field to posts

Revision ID: cced51142379
Revises: 5fe82ffd4a6d
Create Date: 2026-01-06 02:56:45.790833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cced51142379'
down_revision: Union[str, Sequence[str], None] = '5fe82ffd4a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.Text(), nullable=False))
    op.add_column('posts', sa.Column('featured', sa.Boolean(), nullable=False))
    op.drop_column('posts', 'tldr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tldr', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'featured')
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
